### ISSUE TITLE
GPGPUSim prints multiple __cudaPushCallConfiguration and segfaults

### ISSUE THREAD

**Issue by ishitachaturvedi** [gpgpu-sim/gpgpu-sim_distribution#249]
After building GPGPUSim and adding --cudart shared on running GPGPUSim it prints the system configuration followed by  multiple-
"GPGPU-Sim PTX: CUDA API function "unsigned int __cudaPushCallConfiguration(dim3, dim3, size_t, CUstream_st*)" has been called"
and seg faults

**Comment by dmytro1977** [comment]
Yep, today I have the same.
I'm trying to run CUDA sample "vectorAdd" (CUDA 11.6) in release mode at Ubuntu.
I have no video card (integrated Intel one).

**Comment by dmytro1977** [comment]
sorry, looks like the issue is duplicated
can someone kindly point to a good and final resolution of the issue?

**Comment by Dazhuzhu-github** [comment]
Me too， I also run over this question, I run on the wls2 with Ubuntu 18.04 and Cuda 11.06, using the RTX2060s' gpgpusim-config

**Comment by yyctw** [comment]
I can't run GPGPU-Sim in Cuda version 11.0 or above, too.
My workaround was to run GPGPU-Sim on Cuda 10.0 (with Ubuntu 20.04 and g/g++ 7).

**Comment by Dazhuzhu-github** [comment]
I solve the problem now by reinstalling the dependency, and dealing with the GCC g++ version.
I found that the dependency of the dependency has the version conflict, hence making the segfaults.
otherwise, I also found that my gcc and g++ were different versions.
I thought that maybe the two points are why the problems happened.
I solve the problem under the env of wls2 ubuntu 18.04, cuda 11.06.

**Comment by 4mod3** [comment]
> I solve the problem now by reinstalling the dependency, and dealing with the GCC g++ version. I found that the dependency of the dependency has the version conflict, hence making the segfaults. otherwise, I also found that my gcc and g++ were different versions. I thought that maybe the two points are why the problems happened. I solve the problem under the env of wls2 ubuntu 18.04, cuda 11.06.

Can you elaborate the `the dependency of the dependency has the version conflict` ?
I also have the segfaults problem with same version g++ and gcc in 11.2.0, cuda in 11.6. Thank you!

**Comment by gyaneshg96** [comment]
Hey, can you tell exactly which dependency was the issue with? I am running gpgpus-sim in wsl ubuntu 20.06, cuda 11.4. I am getting similar errors. My g++/gcc are both version 9.4.0

**Comment by Dazhuzhu-github** [comment]
> > I solve the problem now by reinstalling the dependency, and dealing with the GCC g++ version. I found that the dependency of the dependency has the version conflict, hence making the segfaults. otherwise, I also found that my gcc and g++ were different versions. I thought that maybe the two points are why the problems happened. I solve the problem under the env of wls2 ubuntu 18.04, cuda 11.06.
> 
> Can you elaborate the `the dependency of the dependency has the version conflict` ? I also have the segfaults problem with same version g++ and gcc in 11.2.0, cuda in 11.6. Thank you!

like this

The following packages have unmet dependencies:
 libglu1-mesa-dev : Depends: libglu1-mesa (= 9.0.0-2.1build1) but 9.0.1-1build1 is to be installed
 zlib1g-dev : Depends: zlib1g (= 1:1.2.11.dfsg-0ubuntu2) but 1:1.2.11.dfsg-2ubuntu1.2 is to be installed
E: Unable to correct problems, you have held broken packages.

and also i change the dependency of libglut3-dev into freeglut3-dev cause i couldn't install the libglut3-dev successfully

**Comment by Dazhuzhu-github** [comment]
I wrote a tutorial of the installation of gpgpusim, but is in chinese, the link is
https://gitee.com/dazhuzhu-gitee/gpgpusim-document/blob/master/document/GPGPU-Sim%E5%AE%89%E8%A3%85%E7%AE%80%E6%98%93%E6%95%99%E7%A8%8B_Au.md

**Comment by gyaneshg96** [comment]
Hey,
Thanks a lot! I figured it out mostly but still thanks

Gyanesh

**Comment by pal-stdr** [comment]
> Hey, Thanks a lot! I figured it out mostly but still thanks Gyanesh

Hello
Every one & @gyaneshg96 
I am stuck in the same issue? Could you please let me know how did you solve it?
My setup
Ubuntu 20.04
CUDA - 11.8

I have tried gcc & g++ version 7.5.0 & 7.5.0
But no luck.

Thanks in advance!
Pallab

**Comment by gyaneshg96** [comment]
I used a docker environment to run the simulator. It has a lower version of
cuda and gcc, but was enough for my purposes.


Gyanesh

**Comment by mushihao** [comment]
I met the same issue and resolved with re-compiled gpgpu-sim with debug option. If you see the same issue, please try with:
>source setup_environment debug
>make

My set is:
WSL2 Ubuntu 20.04
g++ 9.3.0
cuda 11.0

**Comment by chiranchimmili** [comment]
Still experiencing this error
Ubuntu 20.04
CUDA 11.0
gcc/g++ 9.4

Anyone have suggestions?

FIXED: source setup_environment debug

**Comment by vgeraei** [comment]
Are there any fixes for this issue other than compiling GPGPU-Sim in debug mode? 

My setup:
Ubuntu 20.04
CUDA 11.8
gcc/g++ 8.4

I need to run GPGPU-Sim for multiple time-consuming benchmarks and debug mode just takes too long to simulate.

**Comment by quadpixels** [comment]
It seems to be because [this line](https://github.com/gpgpu-sim/gpgpu-sim_distribution/blob/master/libcuda/cuda_runtime_api.cc#L3598) lacks a `return` statement, adding it fixes this issue with a release build

Before:
`cudaConfigureCallInternal(gridDim, blockDim, sharedMem, stream);`

After:
`return cudaConfigureCallInternal(gridDim, blockDim, sharedMem, stream);`
